# Generated by Django 4.2.7 on 2023-12-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("nickname", models.CharField(max_length=20, verbose_name="닉네임")),
                (
                    "id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="아이디",
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="비밀번호")),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
